version: "3.0"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
#      - db_data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: misha
      MYSQL_DATABASE: myimdb
      MYSQL_USER: misha
      MYSQL_PASSWORD: misha

#volumes:
#  db_data: {}